extensions regarding datadog tags
DVPE-cloud/dvpe-helm pull request #15
Opened 2021-03-04 11:52 UTC by jensbac

Extended `dvpe-deployment-gloo/templates/deployment.yaml` by adding tags `env`, `service` and `version` for DataDog according to https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging.

2021-03-04 12:27 UTC, herrLierb commented on charts/dvpe-deployment-gloo/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ if .Values.datadog.version }}{{- .Values.datadog.version }}{{- else }}{{- .Values.deployment.spec.image.tag }}{{- end }}
why give the possibility to override the image tag version at all and not just use it always?

2021-03-04 12:47 UTC, herrLierb approved these changes

2021-03-04 15:33 UTC, christodo requested changes
Please check the ternary case. But besides that, it looks good to me

2021-03-06 08:48 UTC, jensbac commented on charts/dvpe-deployment-gloo/templates/deployment.yaml
> +    tags.datadoghq.com/version: {{ if .Values.datadog.version }}{{- .Values.datadog.version }}{{- else }}{{- .Values.deployment.spec.image.tag }}{{- end }}
replaced by `default` which indeed meets the intention here

2021-03-06 08:48 UTC, jensbac commented on charts/dvpe-deployment-gloo/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ if .Values.datadog.version }}{{- .Values.datadog.version }}{{- else }}{{- .Values.deployment.spec.image.tag }}{{- end }}
replaced by `default` which indeed meets the intention here

2021-03-08 07:34 UTC, christodo approved these changes

2021-03-08 08:49 UTC, merged